name = "echotap-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

[vars]
WORKERS_RS_VERSION = "0.0.18"

[build]
command = "cargo install --git https://github.com/jdgo-mars/echotap-worker worker-build && worker-build --release"